-- Batch 1: USE statement
USE DBTest2;
GO

-- Batch 2: CREATE PROCEDURE statement
CREATE PROCEDURE SP_I_CATEGORIA01
    @CAT_NOMBRE varchar(150),
    @CAT_OBSERVACION varchar(150)
AS
BEGIN
    INSERT INTO TM_CATEGORIAS
        (CAT_NOMBRE, CAT_OBSERVACION)
    VALUES(@CAT_NOMBRE, @CAT_OBSERVACION);

    SELECT *
    FROM TM_CATEGORIAS;
END;
GO
